spring:
  profiles:
    active: "dev"
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


  #  devtools
  debug: true
  spring:
    devtools:
      restart:
        enabled: true  #设置开启热部署
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效




mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      select-strategy: not-null
      update-strategy: not-empty
      insert-strategy: not-empty